version: "3.8"
services:
    lab:
        build: ./lab
        container_name: ctf_lab_1
        ports:
            - 8080:80
        volumes:
            - ./lab/src:/var/www/html
        restart: always
        links:
            - "db"
    db:
        build: ./db
        restart: always
        container_name: db1
        expose:
            - 3306
        environment:
            - MYSQL_HOSTNAME=db
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_USER=db_user
            - MYSQL_PASSWORD=db_password
        command:  --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
