version: "3.8"
services:
    lab:
        build: ./lab
        container_name: test
        ports:
            - 8888:80
        restart: always
        links:
            - "db"
        networks:
            ctf_network:
                ipv4_address: 172.30.10.30 

    db:
        build: ./db
        restart: always
        container_name: db2
        expose:
            - 3306
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_USER=user
            - MYSQL_PASSWORD=pass
        command:  --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        networks:
            ctf_network:
                ipv4_address: 172.30.0.3
    load_balancer:
        build: ./load_balancer
        ports:
          - 9999:80
        depends_on:
            - lab
        networks:
            ctf_network:
                ipv4_address: 172.30.10.40

networks:
    ctf_network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.30.0.0/16
