version: "3.8"
services:
    lab:
        build: ./lab
        container_name: ctf_lab_3
        ports:
            - 10001:80
        restart: always
        links:
            - "db"

    db:
        build: ./db
        restart: always
        container_name: db3
        expose:
            - 3306
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_USER=user
            - MYSQL_PASSWORD=pass
        command:  --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
